create database BANKING_SYSTEM;-- CREATED A DATABASE
use BANKING_SYSTEM;-- ACCESSED THE DATABASE
show DATABASES;
SHOW	TABLES;

CREATE TABLE CUSTOMERS1(
CUSTOMER_ID int,
FIRSTNAME VARCHAR(50),
LASTNAME varchar(50),
EMAIL varchar(100),
PHONE VARCHAR(10));

describe TABLE CUSTOMERS1;
describe CUSTOMERS1;
 
alter table CUSTOMERS1
ADD column ACCOUNT_CREATION_DATE date;

create table ACCOUNTS(
ACCOUNT_ID INT,
ACCOUNT_TYPE VARCHAR(20),
BALANCE decimal(10,2));

CREATE table TRANSACTIONS(
TRANSACTION_ID INT,
TRANSACTION_DATE date,
AMOUNT decimal(10,2),
TRANSACTION_TYPE varchar(20));

CREATE table BRANCHES(
BRANCH_ID INT,
BRANCH_NAME VARCHAR(100),
BRANCH_ADDRESS varchar(255),
BRANCH_PHONE VARCHAR(20));

CREATE TABLE ACCOUNT_BRANCHES(
ASSIGNED_DATE DATE);

CREATE TABLE LOAN(
LOAN_ID INT,
LOAN_AMOUNT decimal(10,2),
INTERST_RATE DECIMAL(5,2),
START_DATE DATE,
END_DATE DATE);
SHOW tables;

DROP TABLE  CUSTOMERS;
DROP TABLE  LOANS;

ALTER table CUSTOMERS1
DROP COLUMN ACCOUNT_CREATION_DATE;

ALTER table CUSTOMERS1
ADD COLUMN BIRTH_DATE DATE;

ALTER TABLE CUSTOMERS1
modify PHONE varchar(20),
ADD primary key(CUSTOMER_ID);

describe CUSTOMERS1;

ALTER TABLE CUSTOMERS1
RENAME COLUMN FIRSTNAME TO FIRST_NAME;

ALTER TABLE CUSTOMERS1
RENAME COLUMN LASTNAME TO LAST_NAME;

DROP TABLE ACCOUNT_BRANCHES;

SELECT * FROM ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD CUSTOMER_ID INT;

ALTER TABLE ACCOUNTS
ADD constraint 
foreign key (CUSTOMER_ID )
references CUSTOMERS1(CUSTOMER_ID);

describe ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD primary key (ACCOUNT_ID);

ALTER TABLE TRANSACTIONS
ADD ACCOUNT_ID INT ,
ADD constraint 
foreign key (ACCOUNT_ID )
references ACCOUNTS(ACCOUNT_ID);

describe ACCOUNTS;

ALTER TABLE TRANSACTIONS
ADD primary key(TRANSACTION_ID);

describe TRANSACTIONS;

ALTER TABLE BRANCHES 
ADD primary key (BRANCH_ID);

ALTER TABLE ACCOUNTS
ADD BRANCH_ID INT ,
ADD constraint 
foreign key (BRANCH_ID )
references BRANCHES(BRANCH_ID);

describe BRANCHES;
describe LOANS;

ALTER TABLE LOAN
ADD primary key (LOAN_ID),
add CUSTOMER_ID INT,
ADD constraint
FOREIGN KEY(CUSTOMER_ID)
references CUSTOMERS1(CUSTOMER_ID);

alter TABLE CUSTOMERS1
modify FIRST_NAME varchar(50)NOT NULL,
modify EMAIL varchar(100)UNIQUE;

describe CUSTOMERS1;

