create database BANKING_SYSTEM;-- CREATED A DATABASE
use BANKING_SYSTEM;-- ACCESSED THE DATABASE
show DATABASES;
SHOW	TABLES;

CREATE TABLE CUSTOMERS1(
CUSTOMER_ID int,
FIRSTNAME VARCHAR(50),
LASTNAME varchar(50),
EMAIL varchar(100),
PHONE VARCHAR(10));

describe TABLE CUSTOMERS1;
describe CUSTOMERS1;
 
alter table CUSTOMERS1
ADD column ACCOUNT_CREATION_DATE date;

create table ACCOUNTS(
ACCOUNT_ID INT,
ACCOUNT_TYPE VARCHAR(20),
BALANCE decimal(10,2));

CREATE table TRANSACTIONS(
TRANSACTION_ID INT,
TRANSACTION_DATE date,
AMOUNT decimal(10,2),
TRANSACTION_TYPE varchar(20));

CREATE table BRANCHES(
BRANCH_ID INT,
BRANCH_NAME VARCHAR(100),
BRANCH_ADDRESS varchar(255),
BRANCH_PHONE VARCHAR(20));

CREATE TABLE ACCOUNT_BRANCHES(
ASSIGNED_DATE DATE);

CREATE TABLE LOAN(
LOAN_ID INT,
LOAN_AMOUNT decimal(10,2),
INTERST_RATE DECIMAL(5,2),
START_DATE DATE,
END_DATE DATE);
SHOW tables;

DROP TABLE  CUSTOMERS;
DROP TABLE  LOANS;

ALTER table CUSTOMERS1
DROP COLUMN ACCOUNT_CREATION_DATE;

ALTER table CUSTOMERS1
ADD COLUMN BIRTH_DATE DATE;

ALTER TABLE CUSTOMERS1
modify PHONE varchar(20),
ADD primary key(CUSTOMER_ID);

describe CUSTOMERS1;

ALTER TABLE CUSTOMERS1
RENAME COLUMN FIRSTNAME TO FIRST_NAME;

ALTER TABLE CUSTOMERS1
RENAME COLUMN LASTNAME TO LAST_NAME;

DROP TABLE ACCOUNT_BRANCHES;

SELECT * FROM ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD CUSTOMER_ID INT;

ALTER TABLE ACCOUNTS
ADD constraint 
foreign key (CUSTOMER_ID )
references CUSTOMERS1(CUSTOMER_ID);

describe ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD primary key (ACCOUNT_ID);

ALTER TABLE TRANSACTIONS
ADD ACCOUNT_ID INT ,
ADD constraint 
foreign key (ACCOUNT_ID )
references ACCOUNTS(ACCOUNT_ID);

describe ACCOUNTS;

ALTER TABLE TRANSACTIONS
ADD primary key(TRANSACTION_ID);

describe TRANSACTIONS;

ALTER TABLE BRANCHES 
ADD primary key (BRANCH_ID);

ALTER TABLE ACCOUNTS
ADD BRANCH_ID INT ,
ADD constraint 
foreign key (BRANCH_ID )
references BRANCHES(BRANCH_ID);

describe BRANCHES;
describe LOANS;

ALTER TABLE LOAN
ADD primary key (LOAN_ID),
add CUSTOMER_ID INT,
ADD constraint
FOREIGN KEY(CUSTOMER_ID)
references CUSTOMERS1(CUSTOMER_ID);

alter TABLE CUSTOMERS1
modify FIRST_NAME varchar(50)NOT NULL,
modify EMAIL varchar(100)UNIQUE;

describe CUSTOMERS1;

-- ADDING RECORDS INSIDE THE TABLES
SELECT * FROM CUSTOMERS1;
SHOW TABLES ;
------------------------------------------------
INSERT INTO CUSTOMERS1 VALUES
(103, 'ROHIT', 'PALVE', 'rohit.palve@gmail.com', '9372506021', '2003-06-12'),
(104, 'OM', 'SHINDE', 'OM.shinde@gmail.com', '9372506022', '2003-07-15'),
(105, 'AKASH', 'PATIL', 'akash.patil@gmail.com', '9372506023', '2002-11-20');


INSERT INTO CUSTOMERS1 VALUES
(106, 'AMIT', 'JADHAV', 'amit.jadhav@gmail.com', NULL, '2003-06-12'),
(107, 'PRIYA', NULL, 'priya.deshmukh@gmail.com', '9372506022', '2003-07-15'),
(108, 'NEHA', 'KULKARNI', NULL, '9372506023', '2002-11-20');

-------------------------------------------------

INSERT INTO BRANCHES (BRANCH_ID, BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE)
VALUES
(101, ' MUMBAI MAIN BRANCH', 'ANDHERI EAST, MUMBAI', '0220100201'),
(102, 'PUNE CENTRAL BRANCH', 'SHIVAJI NAGAR, PUNE', '0220100202'),
(103, 'BANGLORE BRANCH', 'MG ROAD , BANGLORE', '9876543212'),
(104, 'DELHI BRANCH', 'CONNAUGHT PALACE, DELHI ', NULL),
(105, 'HYDERABAD BRANCH', NULL, '9876543214');

SELECT * FROM BRANCHES;

---------------------------------------------
SET FOREIGN_KEY_CHECKS =0;
---------------------------------------------
INSERT INTO ACCOUNTS VALUES
(1001,'SAVINGS',2500,101,1),
(1002,'CURRENT',85000,102,2),
(1003,'SAVINGS',12500,103,1),
(1004,'SALARY',45000,104,3),
(1005,'SAVINGS',7800.25,105,2),
(1006,'SAVINGS',42000,101,2),
(1007,'CURRENT',NULL,103,3),
(1008,'SAVINGS',27500,105,4);

SELECT * FROM ACCOUNTS;
--------------------------------------------
INSERT INTO TRANSACTIONS VALUES
(5001,'2026-01-05',10000,'DEPOSIT',1001),
(5002,'2026-01-10',2500,'WITHDRAWL',1001),
(5003,'2026-01-15',5000,'TRANSFER',1002),
(5004,'2026-01-20',15000,'DEPOSIT',1003),
(5005,'2026-01-25',3000,'WITHDRAWL',1004),
(5006,'2026-01-02',75000,'DEPOSIT',1005),
(5007,'2026-02-05',12000,'PAYMENT',1006),
(5008,'2026-02-10',null,'DEPOSIT',1007),
(5009,'2026-01-05',85000,'WITHDRAWL',1008),
(5010,NULL,1000,'PAYMENT',1009),
(5011,'2026-01-20',20000,'TRANSFER',1006),
(5012,'2026-03-01',5000,'DEPOSIT',1002),
(5013,'2026-03-05',10000,'WITHDRAWL',1007),
(5014,'2026-03-05',1500,'DEPOSIT',1008),
(5015,'2026-03-05',25000,'TRSNSFER',1005);

--------------------------------------------

INSERT INTO LOAN VALUES
(9001,500000,8.50,'2025-01-15','2030-01-15',1001),
(9002,250000,9.25,'2025-03-10','2030-03-10',1003),
(9003,NULL,9.00,'2026-03-01',NULL,105),
(9004,75000,7.90,'2024-06-20','2031-06-20',1002),
(9005,1000000,7.25,'2024-11-15','2034-11-15',1004),
(9006,300000,10.50,'2025-07-01','2029-07-01',1001);

SELECT * FROM LOAN;

---------------------------------------------
SELECT * FROM CUSTOMERS1;
SELECT * FROM TRANSACTIONS;
SELECT * FROM BRANCHES ;
SELECT * FROM ACCOUNTS;

/* UPDATE / DELETING RECORDS */

UPDATE CUSTOMERS1
SET PHONE = "9869868123"
WHERE CUSTOMER_ID =108; -- UPDATED PHONE A NUMBER

DELETE FROM TRANSACTIONS 
WHERE TRANSACTION_ID =5008; -- DELETED A USELESS RECORDS

UPDATE ACCOUNTS
SET BALANCE =35750
WHERE ACCOUNT_ID = 1007; -- UPDATED BALANCE

UPDATE TRANSACTIONS
SET ACCOUNT_ID = 1003
WHERE TRANSACTION_ID IN (5006,5007); -- UPDATED MANY RECORDS

-- EXTRACTING DATA

SELECT *, FIRST_NAME,EMAIL,CUSTOMER_ID
FROM CUSTOMERS1;

SELECT * 
FROM CUSTOMERS1 
WHERE CUSTOMER_ID = 105;  -- CALLING SPECIFIC DATA

SELECT * 
FROM CUSTOMERS1 
WHERE CUSTOMER_ID = 102 OR CUSTOMER_ID =104; -- CALLING MULTIPLE ID

SELECT * 
FROM CUSTOMERS1
WHERE BIRTH_DATE>='1995-01-01' AND BIRTH_DATE<='2000-12-31'; -- CALLING DATA IN RANGES

------------------------------------------------------------------

-- CUSTOMER ANALYSIS 
-- HOW MANY CUSTOMERS ARE THERE ?
SELECT count(*) AS TOTAL_CUSTOMERS -- COLUMN ALISES
FROM CUSTOMERS1;

-- WHICH CUSTOMERS HAVING MISSING INFORMATION ?

SELECT CUSTOMER_ID,FIRST_NAME AS NAME 
FROM CUSTOMERS1
WHERE LAST_NAME IS NULL OR EMAIL IS NULL;

-- WHO ARE YOUNGEST/OLDEST CUSTOMERS ?

SELECT 
max(BIRTH_DATE) AS YOUNGEST_CUSTOMERS,
min(BIRTH_DATE) AS OLDEST_CUSTOMERS
FROM CUSTOMERS1;

-- HOW MANY CUSTOMERS WERE BORN BEFORE / AFTER A PARTICULAR YEAR ?

-- BEFORE 2000

SELECT * FROM CUSTOMERS1
WHERE year(BIRTH_DATE)<2000;

-- AFTER 2000

SELECT * FROM CUSTOMERS1
WHERE year(BIRTH_DATE)>2000;

-- WHICH CUSTOMERS HAVE MULTIPLE ACCOUNTS ?

SELECT  CUSTOMER_ID ,COUNT(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS 
group by CUSTOMER_ID
HAVING TOTAL_ACCOUNTS > 1;

-- ACCOUNT ANALYSIS 

-- HOW MANY SAVINGS, CURRENT AND SALARY ACCOUNTS EXITS ?

SELECT ACCOUNT_TYPE ,count(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS
group by ACCOUNT_TYPE;

-- WHAT IS THE TOTAL BALANCE ?

SELECT SUM(BALANCE) TOTAL_BALANCE
FROM ACCOUNTS ;

-- WHAT IS THE AVERAGE ACCOUNT BALANCE ?

SELECT avg(BALANCE) AVERAGE_BALANCE 
FROM ACCOUNTS;

SELECT CUSTOMER_ID,BALANCE AVERAGE_BALANCE 
FROM ACCOUNTS;

-- WHICH CUSTOMERS HAVE THE HIGHEST BALANCES ?

SELECT CUSTOMER_ID ,BALANCE HIGHEST_BALANCE
FROM ACCOUNTS
order by  BALANCE  DESC LIMIT 1;

-- WHICH ACCOUNT HAVE NULL VALUE ?

SELECT *
 FROM ACCOUNTS
 WHERE BALANCE = NULL; 

-- WHICH BRANCH MANAGES THE MOST ACCOUNTS ?

SELECT BRANCH_ID ,count(*) TOTAL_ACCOUNTS
FROM ACCOUNTS
group by BRANCH_ID
order by TOTAL_ACCOUNTS DESC LIMIT 1;

-- TRANSACTION ANALYSIS

-- WHAT IS THE TOTAL TRANSACTION AMOUNT ?

SELECT sum(AMOUNT)TOTAL_TRANSACTION_AMOUNT 
FROM TRANSACTIONS; 

-- HOW MANY DEPOSIT/WITHDRAWLS/TRANSFER ARE THERE ? 

SELECT 
TRANSACTION_TYPE,
COUNT(*) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
WHERE TRANSACTION_TYPE IN ('DEPOSIT','WITHDRAWL','TRANSFER')
GROUP BY TRANSACTION_TYPE;

-- WHICH TRANSCATION TYPE HAS THE HIGHEST VOLUME ?

 SELECT 
 TRANSACTION_TYPE,
 COUNT(*) AS TOTAL_VALUE
 FROM TRANSACTIONS
 group by TRANSACTION_TYPE 
 order by TRANSACTION_TYPE DESC LIMIT 1;
 
 -- WHICH ACCOUNT HAS HIGHEST TRANSACTION ACTIVITY
 
  SELECT 
ACCOUNT_ID,
 COUNT(*) AS TOTAL_TRANSACTIONS
 FROM TRANSACTIONS
 group by  ACCOUNT_ID
 order by TOTAL_TRANSACTIONS DESC LIMIT 1;
 
-- WHAT IS THE AVERAGE OF TRANSACTION AMOUNT ?
 
SELECT avg(AMOUNT) AS AVERAGE_TRANSACTIONN_AMOUNT 
FROM TRANSACTIONS;

-- WHICH TRANSACTIONS HAVING MISSING DATE / AMOUNT ?

SELECT * FROM TRANSACTIONS 
WHERE TRANSACTION_DATE IS NULL OR AMOUNT IS NULL;

-- LOAN ANALYSIS 

-- WHAT IS TOTAL LOAN  AMOUNT

SELECT  SUM(LOAN_AMOUNT) AS TOTAL_LOAN_AMOUNT FROM LOAN;

-- WHICH CUSTOMERS HAVE LARGEST LOAN ?

SELECT 
CUSTOMER_ID,
MAX(LOAN_AMOUNT) AS LARGEST_LOAN
FROM LOAN
GROUP BY CUSTOMER_ID
ORDER BY LARGEST_LOAN DESC LIMIT 1;

-- WHICH LOAN HAS THE HIGHEST INTREST RATE ?

SELECT
CUSTOMER_ID,
MAX(INTERST_RATE) AS HIGHEST_INTEREST_RATE
FROM LOAN
GROUP BY CUSTOMER_ID
ORDER BY HIGHEST_INTEREST_RATE DESC LIMIT 1;

-- WHICH LOAN ARE STILL ACTIVE ?

SELECT *
FROM LOAN
WHERE END_DATE >=2026-8-3;

-- WHICH CUSTOMERS HAVE MULTIPLE LOANS

SELECT 
CUSTOMER_ID ,COUNT(*) AS MULTIPLE_LOANS
FROM LOAN
group by CUSTOMER_ID
ORDER BY MULTIPLE_LOANS DESC LIMIT 1;
SELECT * FROM LOAN;

-- WHAT IS THE AVERAGE LOAN AMOUNT ?

SELECT avg(LOAN_AMOUNT) 
AS AVERAGE_LOANS FROM LOAN;

-- BRANCH ANALYSIS

-- WHICH BRANCH HAS MOST CUSTOMERS / ACCOUNTS 

SELECT BRANCH_ID , COUNT(*) AS MOST_CUSTOMERS_ACCOUNTS
FROM ACCOUNTS
GROUP BY BRANCH_ID
order by MOST_CUSTOMERS_ACCOUNTS DESC LIMIT 1;
SELECT * FROM BRANCHES;

-- WHICH BRANCH HAS THE HIGGEST  TOTAL ACCOUNT BALANCE ?

SELECT BRANCH_ID,  
max(BALANCE) AS ACCOUNT_BALANCE 
FROM ACCOUNTS
group by BRANCH_ID
ORDER BY ACCOUNT_BALANCE DESC LIMIT 1;

-- WHICH BRANCH HANDLES THE MOST TRANSACTIONS

SELECT  ACCOUNT_ID,
COUNT(TRANSACTION_ID) AS MOST_TRANSACTION 
FROM TRANSACTIONS
group by ACCOUNT_ID
ORDER BY MOST_TRANSACTION  DESC LIMIT 1;

SELECT BRANCH_ID FROM ACCOUNTS WHERE ACCOUNT_ID =1003; 

SELECT * FROM ACCOUNTS;
SELECT * FROM BRANCHES;
SELECT * FROM LOAN ;


--  WHICH BRANCH HAS HIGHEST LOAN EXPOSURE

SELECT CUSTOMER_ID,
MAX(LOAN_AMOUNT) AS TOTAL_LOAN_EXPOSURE
FROM LOAN
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_LOAN_EXPOSURE DESC LIMIT 1;

SELECT BRANCH_ID FROM ACCOUNTS WHERE CUSTOMER_ID =104;


-- FUNCTIONS

-- STRING FUNCTIONS

-- CONCAT ----------------------------------------------------------

SELECT CUSTOMER_ID,concat(FIRST_NAME," ",LAST_NAME) AS FULL_NAME
FROM CUSTOMERS1;

-- UPPER CASE ()------------------------------------------------------------- 

SELECT CUSTOMER_ID,UPPER(concat(FIRST_NAME," ",LAST_NAME) )AS FULL_NAME
FROM CUSTOMERS1;

-- LOWER CASE ()------------------------------------------------------------- 

SELECT CUSTOMER_ID,LOWER(concat(FIRST_NAME," ",LAST_NAME) )AS FULL_NAME
FROM CUSTOMERS1;  

-- LENGTTH  ()---------------------------------------------------------------
-- FIND THE NUMBER LENGTH

SELECT FIRST_NAME,length(FIRST_NAME) AS NAME_LENGTH
FROM CUSTOMERS1
order by NAME_LENGTH DESC;

SELECT FIRST_NAME,length(FIRST_NAME) AS NAME_LENGTH
FROM CUSTOMERS1
HAVING NAME_LENGTH <5
order by NAME_LENGTH DESC LIMIT 1 offset 2; -- OFFSET IS USE TO SKIP THIS VALUES

-- CHAR_LENGTH()------------------------------------------------------

-- CALCULATE THE NUMBER OF STRINGS 

SELECT FIRST_NAME,char_length(FIRST_NAME) AS CHARACTER_LENGTH
FROM CUSTOMERS1;

SELECT char_length("EMP01");

-- LEFT()--------------------------------------------------------------
-- EXTRECT THE DATA FROM LEFT SIDE
SELECT FIRST_NAME,left(FIRST_NAME,3) AS FIRST_3_CHAR
FROM CUSTOMERS1;

-- RIGHT()--------------------------------------------------------------
-- EXTRACT THE DATA FROM RIGHT SIDE

SELECT PHONE,RIGHT(PHONE,4) AS LAST4DIGITS
FROM CUSTOMERS1;

SELECT CUSTOMER_ID,FIRST_NAME ,concat('XXXXX',RIGHT(PHONE,4)) AS MASKED_PHONE
FROM CUSTOMERS1;

-- SUBSTRING()------------------------------------------------------------
-- IT EXTRACTS THE PORTION OF A STRING 

SELECT EMAIL,substring(EMAIL,1,5) AS EMAIL_PART
FROM CUSTOMERS1;

-- SUBSTRING_INDEX()

SELECT EMAIL,substring_index(EMAIL,"@",1) AS EMAIL_PART
FROM CUSTOMERS1;

-- TRIM()------------------------------------------------------------------
-- REMOVE USELESS SPACES

SELECT trim("TEJAS PALVE                 ")AS NAME
FROM CUSTOMERS1;

-- REPLACE()--------------------------------------------------------------
-- REPLACE TE VALUE 

SELECT EMAIL,REPLACE(EMAIL,"GMAIL.COM","EMAIL.COM") AS EMAILS 
FROM CUSTOMERS1;

-- LOCATE()----------------------------------------------------------------
-- FIND THE POSITION OF THE CHARACTER/STING

SELECT EMAIL,locate('@',EMAIL) AS POSITION
FROM CUSTOMERS1;

-- MATH FUNCTIONS --------------------------------------------------------

-- ROUND () --------------------------------------------------------------
-- R0UND OF THE DECIMAL VALUES
SELECT ACCOUNT_ID,BALANCE,round(BALANCE,0) AS ROUND_BALANCE
FROM ACCOUNTS;

-- CEIL/CELING -----------------------------------------------------------
-- IT ROUND UP THE VALUES 
SELECT BALANCE,ceil(BALANCE) AS ROUND_BALANCE
FROM ACCOUNTS;

-- FLOOR() ---------------------------------------------------------------
-- IT ROUND DOWN THE VALUES

SELECT BALANCE ,floor(BALANCE) AS ROUND_BALANCE
FROM ACCOUNTS;

-- ABS() -----------------------------------------------------------------
-- RETURNS THE ABSOLUTE VALUE 

SELECT ABS(-8877) AS ABSOLUTE_VALUES;

-- MOD () --------------------------------
-- RETURNS REMAINING VALUES

SELECT ACCOUNT_ID,MOD(ACCOUNT_ID,2) AS REMINDER
FROM ACCOUNTS;

SELECT ACCOUNT_ID,MOD (ACCOUNT_ID,2) AS REMINDER ,CASE 
WHEN MOD(ACCOUNT_ID,2)=0 THEN "EVEN"
ELSE "ODD"
END AS ID_TYPE
FROM ACCOUNTS;

-- POWER ---------------------------------------
-- WORK LIKE INDICES
SELECT POWER(2,4) AS RESULT;

-- SQRT()
-- RETURNS THE SQRT VALUES

SELECT BALANCE,SQRT(BALANCE) AS SQRT_BALANCE
FROM ACCOUNTS;

-- GREATEST()
-- COMPARES VALUES

SELECT ACCOUNT_ID,BALANCE,greatest(BALANCE,25000) AS MINIMUM_BALANCE
FROM ACCOUNTS;

-- LEAST()
-- COMPARES VALUES

SELECT ACCOUNT_ID,BALANCE,least(BALANCE,50000) AS MAX_LMIT
FROM ACCOUNTS;

-- CALCULATE ANNUAL INTREST 
SELECT LOAN_ID,LOAN_AMOUNT,INTERST_RATE,ROUND(LOAN_AMOUNT * INTERST_RATE/100,2) AS ANNUAL_INTREST
FROM LOAN;

SELECT * FROM LOAN;

-- LOAN AMMOUNT = INTERST

SELECT LOAN_ID,LOAN_AMOUNT,INTERST_RATE,
ROUND(LOAN_AMOUNT +(LOAN_AMOUNT * INTERST_RATE/100),2)AS PRINCIPAL_PLUSONE_YEAR_INTREST
FROM LOAN;


-- BALANCE CATEGORY 

SELECT ACCOUNT_ID,BALANCE,
CASE
WHEN BALANCE IS NULL THEN "UNKNOOWN"
WHEN BALANCE <10000 THEN "LOW"
WHEN BALANCE <50000 THEN "MEDIUM"
ELSE "HIGH"
END AS BALANCE_CATEGORY
FROM ACCOUNTS;

-- DATE & TIME FUNCTIONS

SELECT curdate() AS TODAYS ; -- TODAYS DATE
SELECT sysdate() AS TODAYS ; -- TODAYS DATE WITH TIME		
	
-- YEAR 

SELECT CUSTOMER_ID,BIRTH_DATE,YEAR(BIRTH_DATE) AS BIRTH_YEAR
FROM CUSTOMERS1;	

-- MONTH ()

SELECT TRANSACTION_ID,TRANSACTION_DATE ,MONTH(TRANSACTION_DATE) TRANSACTION_MONTH
FROM TRANSACTIONS;

-- MONTH NAME ()

SELECT TRANSACTION_ID,TRANSACTION_DATE ,MONTHNAME(TRANSACTION_DATE) TRANSACTION_MONTH
FROM TRANSACTIONS;

-- DAY()

SELECT TRANSACTION_ID,TRANSACTION_DATE ,DAY(TRANSACTION_DATE) DAY_NUMBER
FROM TRANSACTIONS;

-- DAYNAME()

SELECT TRANSACTION_ID,TRANSACTION_DATE ,DAYNAME(TRANSACTION_DATE) DAY_NAME
FROM TRANSACTIONS;

-- QUARTER()
SELECT TRANSACTION_ID,TRANSACTION_DATE ,quarter(TRANSACTION_DATE) QUARTER_NAME
FROM TRANSACTIONS;

SELECT QUARTER(TRANSACRION_DATE) AS QUARTER,COUNT(*) AS TRANSACTION_COUNT,sum(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTION_DATE IS NOT NULL
GROUP BY quarter(TRANSATION_DATE);

-- DATEDIFF()

SELECT LOAN_ID,START_DATE,END_DATE,ROUND(datediff(END_DATE,START_DATE)/365,2) AS LOAN_DAYS
FROM LOAN
WHERE END_DATE IS NOT NULL;

-- TIMESTAMPIFF()
SELECT CUSTOMER_ID,FIRST_NAME,BIRTH_DATE,timestampdiff(YEAR,BIRTH_DATE,CURDATE()) AS AGE
FROM CUSTOMERS1;

-- AGE GROUP9()

SELECT CUSTOMER_ID,FIRST_NAME,BIRTH_DATE,timestampdiff(YEAR,BIRTH_DATE,CURDATE()) AS AGE,
CASE 
WHEN timestampdiff(YEAR,BIRTH_DATE,CURDATE())< 25 THEN "YOUNG ADULT"
WHEN timestampdiff(YEAR,BIRTH_DATE,CURDATE()) BETWEEN 25 AND 40 THEN "ADULT"
ELSE "SENIOR"
END AS AGE_GROUP
FROM CUSTOMERS1;

-- DATEFORMAT()

SELECT TRANSACTION_DATE , date_format(TRANSACTION_DATE,'%d-%m-%y') AS FORMATED_DATE
FROM TRANSACTIONS;

SELECT TRANSACTION_DATE , date_format(TRANSACTION_DATE,'%D-%M-%Y') AS MONTH_YEAR
FROM TRANSACTIONS;

-- MONTHLY TRANSACTIONS

SELECT 
date_format(TRANSACTION_DATE,'%Y-%m') AS MONTH,
COUNT(*) AS TRANSACTION_COUNTS,
sum(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTION_DATE IS NOT NULL
GROUP BY DATE_FORMAT(TRANSACTION_DATE,'%Y-%m')
ORDER BY MONTH;

-- LAST 30 DAYS TRANDACTIONS

SELECT * 
FROM TRANSACTIONS
WHERE TRANSACTION_DATE >= date_sub(curdate(),INTERVAL 30 DAY);

SELECT * 
FROM TRANSACTIONS
WHERE TRANSACTION_DATE >= date_sub('2026-02-25',INTERVAL 30 DAY);

-- ADDING TO THE DATE

SELECT TRANSACTION_ID,TRANSACTION_DATE,DATE_ADD(TRANSACTION_DATE,INTERVAL 30 DAY)AS AFTER_30_DAYS
FROM TRANSACTIONS;

-- LOAN STATUS USING DAYS

SELECT LOAN_ID,START_DATE,END_DATE,
CASE
WHEN END_DATE IS NULL THEN "NO END DATE"
WHEN END_DATE <curdate() THEN "COMPLETED"
ELSE "ACTIVE"
END AS LOAN_STATUS
FROM LOAN;

-- WINDOWS FUNCTIONS
-- RANK() , DENSE_RANK(), OVER ()
SELECT LOAN_ID,LOAN_AMOUNT,RANK() OVER(order by LOAN_AMOUNT DESC) AS LOAN_RANK
FROM LOAN;

SELECT BALANCE FROM ACCOUNTS;

SELECT TRANSACTION_ID ,AMOUNT,RANK() OVER(ORDER BY AMOUNT DESC) AS TRANSACTION_RANK ,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS TRANSACTION_DENSE_RANK
FROM TRANSACTIONS;

SELECT TRANSACTION_ID,TRANSACTION_TYPE,AMOUNT,
DENSE_RANK() OVER(partition by TRANSACTION_TYPE ORDER BY AMOUNT DESC) AS  TRANSACTION_RANK 
from TRANSACTIONS;

-- ROW_NUMBER()

SELECT LOAN_ID ,CUSTOMER_ID,LOAN_AMOUNT,
row_number() OVER(order by LOAN_AMOUNT DESC) AS ROW_NUMBERS
FROM LOAN;

SELECT LOAN_ID,CUSTOMER_ID,LOAN_AMOUNT,
row_number() OVER(partition by CUSTOMER_ID order by LOAN_AMOUNT DESC) AS RN
FROM LOAN;

-- SUM()
SELECT LOAN_ID,CUSTOMER_ID,LOAN_AMOUNT,
SUM(LOAN_AMOUNT) OVER (order by LOAN_AMOUNT DESC) AS RUNNING_TOTAL
FROM LOAN;

SELECT LOAN_ID,CUSTOMER_ID,LOAN_AMOUNT,
SUM(LOAN_AMOUNT) OVER (partition by CUSTOMER_ID ORDER  by LOAN_AMOUNT DESC) AS RUNNING_TOTAL
FROM LOAN;

-- LAG()

SELECT LOAN_ID,CUSTOMER_ID,LOAN_AMOUNT,
LAG(LOAN_AMOUNT) OVER (order by LOAN_AMOUNT DESC) AS PREVIOUS_LOAN_AMOUNT
FROM LOAN;

-- LEAD()

SELECT LOAN_ID,CUSTOMER_ID,LOAN_AMOUNT,
LEAD(LOAN_AMOUNT) OVER (order by LOAN_AMOUNT DESC) AS NEXT_LOAN_AMOUNT
FROM LOAN;


-- INNER JOIN -----------------------------------------------------------------

SELECT * FROM CUSTOMERS1;
SELECT * FROM ACCOUNTS;

SELECT CUSTOMERS1.CUSTOMER_ID,FIRST_NAME,ACCOUNT_TYPE,BALANCE
FROM CUSTOMERS1
JOIN ACCOUNTS
ON CUSTOMERS1.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID;

SELECT C.CUSTOMER_ID,C.FIRST_NAME,COUNT(A.ACCOUNT_ID) AS TOTAL_ACCOUNTS
FROM CUSTOMERS1 AS C
JOIN ACCOUNTS AS A
ON C.CUSTOMER_ID = A.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID;

SELECT * FROM TRANSACTIONS;
SELECT * FROM LOAN;
SELECT * FROM BRANCHES;
SELECT * FROM ACCOUNTS;

SELECT BRANCH_NAME, count(ACCOUNT_ID)
FROM BRANCHES
JOIN ACCOUNTS
ON BRANCHES.BRANCH_ID = ACCOUNTS.BRANCH_ID
GROUP BY BRANCH_NAME;

-- LEFT JOIN

SELECT BRANCH_NAME, count(ACCOUNT_ID) AS TOTAL_ACCOUNTS
FROM BRANCHES
LEFT JOIN ACCOUNTS
ON BRANCHES.BRANCH_ID = ACCOUNTS.BRANCH_ID
GROUP BY BRANCH_NAME;

-- RIGHT JOIN 

SELECT BRANCH_NAME, count(ACCOUNT_ID) AS TOTAL_ACCOUNTS
FROM BRANCHES
RIGHT JOIN ACCOUNTS
ON BRANCHES.BRANCH_ID = ACCOUNTS.BRANCH_ID
GROUP BY BRANCH_NAME;

-- WHICH BRANCH HAS THE  MOST CUSTOMERS/ACCOUNTS ?

SELECT * FROM CUSTOMERS1;
SELECT * FROM ACCOUNTS;
SELECT * FROM BRANCHES;


SELECT BRANCH_NAME,BRANCHES.BRANCH_ID,
COUNT(ACCOUNT_ID) AS TOTAL_ACCOUNTS,
COUNT(CUSTOMERS1.CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM ACCOUNTS
JOIN BRANCHES
ON ACCOUNTS.BRANCH_ID = BRANCHES.BRANCH_ID
JOIN CUSTOMERS1
ON ACCOUNTS.CUSTOMER_ID = CUSTOMERS1.CUSTOMER_ID
GROUP BY BRANCH_ID
order by TOTAL_ACCOUNTS DESC LIMIT 1;

-- WHICH BARNCH HAS HIGHEST LOAN EXPOSURE ?

SELECT * FROM CUSTOMERS1;
SELECT * FROM ACCOUNTS;
SELECT * FROM BRANCHES;
SELECT * FROM LOAN;

SELECT B.BRANCH_ID,BRANCH_NAME,SUM(LOAN_AMOUNT) AS TOTAL_LOANS
FROM BRANCHES AS B
JOIN ACCOUNTS  AS A 
ON B.BRANCH_ID = A.BRANCH_ID
JOIN CUSTOMERS1 AS C
ON A.CUSTOMER_ID =C.CUSTOMER_ID
JOIN LOAN L
ON L.CUSTOMER_ID =C.CUSTOMER_ID
GROUP BY B.BRANCH_ID
order by TOTAL_LOANS DESC LIMIT 1;

-- Distinct ----------------------------------------------------------

select * from accounts;

SELECT count(distinct ACCOUNT_TYPE) AS TOTAL_ACCOUNTS_TYPES
FROM ACCOUNTS;

-- LIKE -------------------------------------------------------------

SELECT * FROM CUSTOMERS1
WHERE FIRST_NAME LIKE 'T%';

select * FROM CUSTOMERS1
WHERE FIRST_NAME LIKE '%EE%';

select * FROM CUSTOMERS1
WHERE FIRST_NAME LIKE '_E%';


select * FROM CUSTOMERS1
WHERE FIRST_NAME LIKE '%S';

-- VIEWS  ----------------------------------------------------

CREATE VIEW CUSTOMER_DETAILS AS
SELECT CUSTOMER_ID,concat(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME,EMAIL,PHONE
FROM CUSTOMERS1;

SELECT * FROM CUSTOMER_DETAILS;

-- CUSTOMER ACCOUNT VIEW

CREATE VIEW CUSTOMER_ACCOUNTS AS 
SELECT C.CUSTOMER_ID,CONCAT(C.FIRST_NAME,'  ' ,C.LAST_NAME) AS FULL_NAME,C.EMAIL
FROM CUSTOMERS1 C 
JOIN ACCOUNTS a
ON C.CUSTOMER_ID =A.CUSTOMER_ID;

SELECT * FROM CUSTOMER_ACCOUNTS;

SELECT * FROM CUSTOMER_ACCOUNTS
WHERE BALANCE > 30000;
-- CUSTOMER - ACCOUNT  SUMMARY

CREATE VIEW CUSTOMER_ACCOUNTS_SUMMARY AS
SELECT  C.CUSTOMER_ID,CONCAT (COALESCE(C.FIRST_NAME,""),'  ' ,COALESCE(C.LAST_NAME,"")) AS CUSTOMER_NAME,
COUNT(A.ACCOUNT_ID) AS TOTAL_ACCOUNTS,
COALESCE(SUM(A.BALANCE),0) AS TOTAL_BALANCE,
COALESCE(ROUND(AVG(A.BALANCE),2),0) AS AVERAGE_BALANCE
FROM CUSTOMERS1 AS C
LEFT JOIN ACCOUNTS AS A
ON A.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME;


SELECT *  FROM CUSTOMER_ACCOUNTS_SUMMARY;

-- CUSTOMERS WHITH HIGHEST BALANVE GREATER THAN 50000
SELECT * FROM CUSTOMER_ACCOUNTS_SUMMARY
WHERE TOTAL_BALANCE > 50000;

-- CUSTOMERS 

SELECT * FROM CUSTOMER_ACCOUNTS_SUMMARY
ORDER BY TOTAL_BALANCE DESC;

-- TOP 3 CUSTOMERS

SELECT * FROM CUSTOMER_ACCOUNTS_SUMMARY
ORDER BY TOTAL_BALANCE DESC
LIMIT 3;

-- TRANSACTION SUMMARY

CREATE VIEW TRANSACTION_SUMMARY AS
SELECT TRANSACTION_TYPE,count(TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
coalesce(sum(AMOUNT),0) AS TOTAL_AMOUNT,
coalesce(avg(AMOUNT),0) AS AVERAGE_AMOUNT,
coalesce(max(AMOUNT),0) AS MAX_AMOUNT,
coalesce(min(AMOUNT),0) AS MIN_AMOUNT
FROM TRANSACTIONS
group by TRANSACTION_TYPE;

SELECT * FROM TRANSACTION_SUMMARY;

-- BRANCH PERFORMANCE

CREATE VIEW BRANCH_PERFORMANCE AS
SELECT B.BRANCH_ID,B.BRANCH_NAME,
COUNT(A.ACCOUNT_ID) AS TOTAL_ACCOUNTS,
coalesce(sum(A.BALANCE),0) AS TOTAL_BALANCE,
COALESCE(AVG(A.BALANCE),0) AS TOTAL_AVERAGE_BALANCE
FROM BRANCHES B
LEFT JOIN ACCOUNTS A 
ON B.BRANCH_ID =A.BRANCH_ID
group by B.BRANCH_ID,B.BRANCH_NAME;

SELECT * FROM BRANCH_PERFORMANCE;

-- LOAN ANALYSIS

CREATE VIEW LOAN_SUMMARY AS
SELECT C.CUSTOMER_ID,
concat(COALESCE(FIRST_NAME,""),"",COALESCE(C.LAST_NAME,"")) AS CUSTOMER_NAME,
COUNT(L.LOAN_ID) AS TOTAL_LOANS,
coalesce(sum(L.LOAN_AMOUNT),0) AS TOTAL_LOAN_AMOUNT,
COALESCE(round(avg(L.LOAN_AMOUNT),2),0) AS AVG_LOAN_AMOUNT,
COALESCE(avg(L.LOAN_AMOUNT),0) AS  AVG_INTREST_RATE
FROM CUSTOMERS1 C 
LEFT join LOAN AS L
ON C.CUSTOMER_ID =L.CUSTOMER_ID
group by C.CUSTOMER_ID,FIRST_NAME,LAST_NAME;

SELECT * FROM LOAN_SUMMARY; 

-- SUBQUERIES----------------------------------------------------------------------------------

SELECT * 
FROM ACCOUNTS
WHERE BALANCE > (SELECT AVG (BALANCE) FROM ACCOUNTS);


SELECT * FROM CUSTOMERS1
WHERE CUSTOMER_ID IN(SELECT CUSTOMER_ID
FROM ACCOUNTS
WHERE BALANCE >(SELECT AVG (BALANCE) FROM ACCOUNTS));

-- ACCOUNT WITH MAX BALANCE

SELECT * FROM ACCOUNTS
WHERE BALANCE =(SELECT MAX(BALANCE)FROM ACCOUNTS);

SELECT * FROM 
BRANCHES
WHERE BRANCH_ID = (SELECT BRANCH_ID
FROM ACCOUNTS
WHERE BALANCE =(SELECT MAX(BALANCE)FROM ACCOUNTS));

-- ACCOUNTS WITH BELOW AVERAGE

SELECT * FROM CUSTOMERS1
WHERE CUSTOMERS_ID NOT IN (SELECT CUSTOMER_ID FROM LOAN);
-- CUSTOMERS  WHO HAVE LOANS

SELECT * FROM CUSTOMERS1
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM LOAN);

-- CUSTOMERS DONT HAVE LOANS 

SELECT * FROM CUSTOMERS1
WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM LOAN);

-- CUSTOMERS MORE THAN ONE LOANS

SELECT * FROM CUSTOMERS1
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM LOAN
GROUP BY CUSTOMER_ID
HAVING COUNT(LOAN_ID)>1);

-- LOAN WITH ABOVE AVERAGE LOAN_AMOUNT -----------

SELECT * FROM  LOAN
WHERE LOAN_AMOUNT > (SELECT AVG (LOAN_AMOUNT) FROM LOAN);

-- LOANS WITH ABOVE AVERAGE INTEREST_RATE

SELECT * FROM  LOAN 
WHERE INTERST_RATE > (SELECT AVG (INTERST_RATE) FROM LOAN);

-- ACCOUNTS BELONGING TO CUSTOMERS WITH LOANS

SELECT * FROM ACCOUNTS
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM LOAN);

SELECT * FROM ACCOUNTS
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM LOAN
GROUP BY CUSTOMER_ID
HAVING COUNT(LOAN_ID));

-- ACCOUNTS WHO HAS GREATER THEN THE AVERAGE BALANCE OF ACCOUNTS OF THE SAME CUSTOMER

SELECT 	A.CUSTOMER_ID,A.ACCOUNT_ID,A.BALANCE
FROM ACCOUNTS A
WHERE BALANCE >(SELECT AVG(BALANCE) 
				FROM ACCOUNTS A1
				WHERE A.CUSTOMER_ID = A1.CUSTOMER_ID);
                
  -- CUSTOMERS WITH ATLEAST ONE ACCOUNTS              

SELECT C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME
FROM CUSTOMERS1 AS C 
WHERE EXISTS (SELECT 1
				FROM ACCOUNTS AS A 
                WHERE A.CUSTOMER_ID =C.CUSTOMER_ID);
                
-- CUSTOMERS WITH ATLEAST ONE ACCOUNTS  

SELECT C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME
FROM CUSTOMERS1 AS C 
WHERE EXISTS (SELECT 1
				FROM ACCOUNTS AS A 
                WHERE A.CUSTOMER_ID =C.CUSTOMER_ID)
AND EXISTS (SELECT 1
				FROM LOAN AS L 
                WHERE L.CUSTOMER_ID =C.CUSTOMER_ID);

-- CUSTOMERS TOTAL BALANCE IS ABOVE CUSTOMERS BALANCE 

SELECT * 
FROM CUSTOMER_ACCOUNTS_SUMMARY 
WHERE TOTAL_BALANCE > (SELECT AVG (TOTAL_BALANCE)FROM CUSTOMER_ACCOUNTS_SUMMARY); 