create database BANKING_SYSTEM;-- CREATED A DATABASE
use BANKING_SYSTEM;-- ACCESSED THE DATABASE
show DATABASES;
SHOW	TABLES;

CREATE TABLE CUSTOMERS1(
CUSTOMER_ID int,
FIRSTNAME VARCHAR(50),
LASTNAME varchar(50),
EMAIL varchar(100),
PHONE VARCHAR(10));

describe TABLE CUSTOMERS1;
describe CUSTOMERS1;
 
alter table CUSTOMERS1
ADD column ACCOUNT_CREATION_DATE date;

create table ACCOUNTS(
ACCOUNT_ID INT,
ACCOUNT_TYPE VARCHAR(20),
BALANCE decimal(10,2));

CREATE table TRANSACTIONS(
TRANSACTION_ID INT,
TRANSACTION_DATE date,
AMOUNT decimal(10,2),
TRANSACTION_TYPE varchar(20));

CREATE table BRANCHES(
BRANCH_ID INT,
BRANCH_NAME VARCHAR(100),
BRANCH_ADDRESS varchar(255),
BRANCH_PHONE VARCHAR(20));

CREATE TABLE ACCOUNT_BRANCHES(
ASSIGNED_DATE DATE);

CREATE TABLE LOAN(
LOAN_ID INT,
LOAN_AMOUNT decimal(10,2),
INTERST_RATE DECIMAL(5,2),
START_DATE DATE,
END_DATE DATE);
SHOW tables;

DROP TABLE  CUSTOMERS;
DROP TABLE  LOANS;

ALTER table CUSTOMERS1
DROP COLUMN ACCOUNT_CREATION_DATE;

ALTER table CUSTOMERS1
ADD COLUMN BIRTH_DATE DATE;

ALTER TABLE CUSTOMERS1
modify PHONE varchar(20),
ADD primary key(CUSTOMER_ID);

describe CUSTOMERS1;

ALTER TABLE CUSTOMERS1
RENAME COLUMN FIRSTNAME TO FIRST_NAME;

ALTER TABLE CUSTOMERS1
RENAME COLUMN LASTNAME TO LAST_NAME;

DROP TABLE ACCOUNT_BRANCHES;

SELECT * FROM ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD CUSTOMER_ID INT;

ALTER TABLE ACCOUNTS
ADD constraint 
foreign key (CUSTOMER_ID )
references CUSTOMERS1(CUSTOMER_ID);

describe ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD primary key (ACCOUNT_ID);

ALTER TABLE TRANSACTIONS
ADD ACCOUNT_ID INT ,
ADD constraint 
foreign key (ACCOUNT_ID )
references ACCOUNTS(ACCOUNT_ID);

describe ACCOUNTS;

ALTER TABLE TRANSACTIONS
ADD primary key(TRANSACTION_ID);

describe TRANSACTIONS;

ALTER TABLE BRANCHES 
ADD primary key (BRANCH_ID);

ALTER TABLE ACCOUNTS
ADD BRANCH_ID INT ,
ADD constraint 
foreign key (BRANCH_ID )
references BRANCHES(BRANCH_ID);

describe BRANCHES;
describe LOANS;

ALTER TABLE LOAN
ADD primary key (LOAN_ID),
add CUSTOMER_ID INT,
ADD constraint
FOREIGN KEY(CUSTOMER_ID)
references CUSTOMERS1(CUSTOMER_ID);

alter TABLE CUSTOMERS1
modify FIRST_NAME varchar(50)NOT NULL,
modify EMAIL varchar(100)UNIQUE;

describe CUSTOMERS1;

-- ADDING RECORDS INSIDE THE TABLES
SELECT * FROM CUSTOMERS1;
SHOW TABLES ;
------------------------------------------------
INSERT INTO CUSTOMERS1 VALUES
(103, 'ROHIT', 'PALVE', 'rohit.palve@gmail.com', '9372506021', '2003-06-12'),
(104, 'OM', 'SHINDE', 'OM.shinde@gmail.com', '9372506022', '2003-07-15'),
(105, 'AKASH', 'PATIL', 'akash.patil@gmail.com', '9372506023', '2002-11-20');


INSERT INTO CUSTOMERS1 VALUES
(106, 'AMIT', 'JADHAV', 'amit.jadhav@gmail.com', NULL, '2003-06-12'),
(107, 'PRIYA', NULL, 'priya.deshmukh@gmail.com', '9372506022', '2003-07-15'),
(108, 'NEHA', 'KULKARNI', NULL, '9372506023', '2002-11-20');

-------------------------------------------------

INSERT INTO BRANCHES (BRANCH_ID, BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE)
VALUES
(101, ' MUMBAI MAIN BRANCH', 'ANDHERI EAST, MUMBAI', '0220100201'),
(102, 'PUNE CENTRAL BRANCH', 'SHIVAJI NAGAR, PUNE', '0220100202'),
(103, 'BANGLORE BRANCH', 'MG ROAD , BANGLORE', '9876543212'),
(104, 'DELHI BRANCH', 'CONNAUGHT PALACE, DELHI ', NULL),
(105, 'HYDERABAD BRANCH', NULL, '9876543214');

SELECT * FROM BRANCHES;

---------------------------------------------
SET FOREIGN_KEY_CHECKS =0;
---------------------------------------------
INSERT INTO ACCOUNTS VALUES
(1001,'SAVINGS',2500,101,1),
(1002,'CURRENT',85000,102,2),
(1003,'SAVINGS',12500,103,1),
(1004,'SALARY',45000,104,3),
(1005,'SAVINGS',7800.25,105,2),
(1006,'SAVINGS',42000,101,2),
(1007,'CURRENT',NULL,103,3),
(1008,'SAVINGS',27500,105,4);

SELECT * FROM ACCOUNTS;
--------------------------------------------
INSERT INTO TRANSACTIONS VALUES
(5001,'2026-01-05',10000,'DEPOSIT',1001),
(5002,'2026-01-10',2500,'WITHDRAWL',1001),
(5003,'2026-01-15',5000,'TRANSFER',1002),
(5004,'2026-01-20',15000,'DEPOSIT',1003),
(5005,'2026-01-25',3000,'WITHDRAWL',1004),
(5006,'2026-01-02',75000,'DEPOSIT',1005),
(5007,'2026-02-05',12000,'PAYMENT',1006),
(5008,'2026-02-10',null,'DEPOSIT',1007),
(5009,'2026-01-05',85000,'WITHDRAWL',1008),
(5010,NULL,1000,'PAYMENT',1009),
(5011,'2026-01-20',20000,'TRANSFER',1006),
(5012,'2026-03-01',5000,'DEPOSIT',1002),
(5013,'2026-03-05',10000,'WITHDRAWL',1007),
(5014,'2026-03-05',1500,'DEPOSIT',1008),
(5015,'2026-03-05',25000,'TRSNSFER',1005);

--------------------------------------------

INSERT INTO LOAN VALUES
(9001,500000,8.50,'2025-01-15','2030-01-15',1001),
(9002,250000,9.25,'2025-03-10','2030-03-10',1003),
(9003,NULL,9.00,'2026-03-01',NULL,105),
(9004,75000,7.90,'2024-06-20','2031-06-20',1002),
(9005,1000000,7.25,'2024-11-15','2034-11-15',1004),
(9006,300000,10.50,'2025-07-01','2029-07-01',1001);

SELECT * FROM LOAN;

---------------------------------------------
SELECT * FROM CUSTOMERS1;
SELECT * FROM TRANSACTIONS;
SELECT * FROM BRANCHES ;
SELECT * FROM ACCOUNTS;

/* UPDATE / DELETING RECORDS */

UPDATE CUSTOMERS1
SET PHONE = "9869868123"
WHERE CUSTOMER_ID =108; -- UPDATED PHONE A NUMBER

DELETE FROM TRANSACTIONS 
WHERE TRANSACTION_ID =5008; -- DELETED A USELESS RECORDS

UPDATE ACCOUNTS
SET BALANCE =35750
WHERE ACCOUNT_ID = 1007; -- UPDATED BALANCE

UPDATE TRANSACTIONS
SET ACCOUNT_ID = 1003
WHERE TRANSACTION_ID IN (5006,5007); -- UPDATED MANY RECORDS

-- EXTRACTING DATA

SELECT *, FIRST_NAME,EMAIL,CUSTOMER_ID
FROM CUSTOMERS1;

SELECT * 
FROM CUSTOMERS1 
WHERE CUSTOMER_ID = 105;  -- CALLING SPECIFIC DATA

SELECT * 
FROM CUSTOMERS1 
WHERE CUSTOMER_ID = 102 OR CUSTOMER_ID =104; -- CALLING MULTIPLE ID

SELECT * 
FROM CUSTOMERS1
WHERE BIRTH_DATE>='1995-01-01' AND BIRTH_DATE<='2000-12-31'; -- CALLING DATA IN RANGES

------------------------------------------------------------------

-- CUSTOMER ANALYSIS 
-- HOW MANY CUSTOMERS ARE THERE ?
SELECT count(*) AS TOTAL_CUSTOMERS -- COLUMN ALISES
FROM CUSTOMERS1;

-- WHICH CUSTOMERS HAVING MISSING INFORMATION ?

SELECT CUSTOMER_ID,FIRST_NAME AS NAME 
FROM CUSTOMERS1
WHERE LAST_NAME IS NULL OR EMAIL IS NULL;

-- WHO ARE YOUNGEST/OLDEST CUSTOMERS ?

SELECT 
max(BIRTH_DATE) AS YOUNGEST_CUSTOMERS,
min(BIRTH_DATE) AS OLDEST_CUSTOMERS
FROM CUSTOMERS1;

-- HOW MANY CUSTOMERS WERE BORN BEFORE / AFTER A PARTICULAR YEAR ?

-- BEFORE 2000

SELECT * FROM CUSTOMERS1
WHERE year(BIRTH_DATE)<2000;

-- AFTER 2000

SELECT * FROM CUSTOMERS1
WHERE year(BIRTH_DATE)>2000;

-- WHICH CUSTOMERS HAVE MULTIPLE ACCOUNTS ?

SELECT  CUSTOMER_ID ,COUNT(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS 
group by CUSTOMER_ID
HAVING TOTAL_ACCOUNTS > 1;

-- ACCOUNT ANALYSIS 

-- HOW MANY SAVINGS, CURRENT AND SALARY ACCOUNTS EXITS ?

SELECT ACCOUNT_TYPE ,count(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS
group by ACCOUNT_TYPE;

-- WHAT IS THE TOTAL BALANCE ?

SELECT SUM(BALANCE) TOTAL_BALANCE
FROM ACCOUNTS ;

-- WHAT IS THE AVERAGE ACCOUNT BALANCE ?

SELECT avg(BALANCE) AVERAGE_BALANCE 
FROM ACCOUNTS;

SELECT CUSTOMER_ID,BALANCE AVERAGE_BALANCE 
FROM ACCOUNTS;

-- WHICH CUSTOMERS HAVE THE HIGHEST BALANCES ?

SELECT CUSTOMER_ID ,BALANCE HIGHEST_BALANCE
FROM ACCOUNTS
order by  BALANCE  DESC LIMIT 1;

-- WHICH ACCOUNT HAVE NULL VALUE ?

SELECT *
 FROM ACCOUNTS
 WHERE BALANCE = NULL; 

-- WHICH BRANCH MANAGES THE MOST ACCOUNTS ?

SELECT BRANCH_ID ,count(*) TOTAL_ACCOUNTS
FROM ACCOUNTS
group by BRANCH_ID
order by TOTAL_ACCOUNTS DESC LIMIT 1;

-- TRANSACTION ANALYSIS

-- WHAT IS THE TOTAL TRANSACTION AMOUNT ?

SELECT sum(AMOUNT)TOTAL_TRANSACTION_AMOUNT 
FROM TRANSACTIONS; 

-- HOW MANY DEPOSIT/WITHDRAWLS/TRANSFER ARE THERE ? 

SELECT 
TRANSACTION_TYPE,
COUNT(*) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
WHERE TRANSACTION_TYPE IN ('DEPOSIT','WITHDRAWL','TRANSFER')
GROUP BY TRANSACTION_TYPE;

-- WHICH TRANSCATION TYPE HAS THE HIGHEST VOLUME ?

 SELECT 
 TRANSACTION_TYPE,
 COUNT(*) AS TOTAL_VALUE
 FROM TRANSACTIONS
 group by TRANSACTION_TYPE 
 order by TRANSACTION_TYPE DESC LIMIT 1;
 
 -- WHICH ACCOUNT HAS HIGHEST TRANSACTION ACTIVITY
 
  SELECT 
ACCOUNT_ID,
 COUNT(*) AS TOTAL_TRANSACTIONS
 FROM TRANSACTIONS
 group by  ACCOUNT_ID
 order by TOTAL_TRANSACTIONS DESC LIMIT 1;
 
-- WHAT IS THE AVERAGE OF TRANSACTION AMOUNT ?
 
SELECT avg(AMOUNT) AS AVERAGE_TRANSACTIONN_AMOUNT 
FROM TRANSACTIONS;

-- WHICH TRANSACTIONS HAVING MISSING DATE / AMOUNT ?

SELECT * FROM TRANSACTIONS 
WHERE TRANSACTION_DATE IS NULL OR AMOUNT IS NULL;

-- LOAN ANALYSIS 

-- WHAT IS TOTAL LOAN  AMOUNT

SELECT  SUM(LOAN_AMOUNT) AS TOTAL_LOAN_AMOUNT FROM LOAN;

-- WHICH CUSTOMERS HAVE LARGEST LOAN ?

SELECT 
CUSTOMER_ID,
MAX(LOAN_AMOUNT) AS LARGEST_LOAN
FROM LOAN
GROUP BY CUSTOMER_ID
ORDER BY LARGEST_LOAN DESC LIMIT 1;

-- WHICH LOAN HAS THE HIGHEST INTREST RATE ?

SELECT
CUSTOMER_ID,
MAX(INTERST_RATE) AS HIGHEST_INTEREST_RATE
FROM LOAN
GROUP BY CUSTOMER_ID
ORDER BY HIGHEST_INTEREST_RATE DESC LIMIT 1;

-- WHICH LOAN ARE STILL ACTIVE ?

SELECT *
FROM LOAN
WHERE END_DATE >=2026-8-3;

-- WHICH CUSTOMERS HAVE MULTIPLE LOANS

SELECT 
CUSTOMER_ID ,COUNT(*) AS MULTIPLE_LOANS
FROM LOAN
group by CUSTOMER_ID
ORDER BY MULTIPLE_LOANS DESC LIMIT 1;
SELECT * FROM LOAN;

-- WHAT IS THE AVERAGE LOAN AMOUNT ?

SELECT avg(LOAN_AMOUNT) 
AS AVERAGE_LOANS FROM LOAN;

-- BRANCH ANALYSIS

-- WHICH BRANCH HAS MOST CUSTOMERS / ACCOUNTS 

SELECT BRANCH_ID , COUNT(*) AS MOST_CUSTOMERS_ACCOUNTS
FROM ACCOUNTS
GROUP BY BRANCH_ID
order by MOST_CUSTOMERS_ACCOUNTS DESC LIMIT 1;
SELECT * FROM BRANCHES;

-- WHICH BRANCH HAS THE HIGGEST  TOTAL ACCOUNT BALANCE ?

SELECT BRANCH_ID,  
max(BALANCE) AS ACCOUNT_BALANCE 
FROM ACCOUNTS
group by BRANCH_ID
ORDER BY ACCOUNT_BALANCE DESC LIMIT 1;

-- WHICH BRANCH HANDLES THE MOST TRANSACTIONS

SELECT  ACCOUNT_ID,
COUNT(TRANSACTION_ID) AS MOST_TRANSACTION 
FROM TRANSACTIONS
group by ACCOUNT_ID
ORDER BY MOST_TRANSACTION  DESC LIMIT 1;

SELECT BRANCH_ID FROM ACCOUNTS WHERE ACCOUNT_ID =1003; 

SELECT * FROM ACCOUNTS;
SELECT * FROM BRANCHES;
SELECT * FROM LOAN ;


--  WHICH BRANCH HAS HIGHEST LOAN EXPOSURE

SELECT CUSTOMER_ID,
MAX(LOAN_AMOUNT) AS TOTAL_LOAN_EXPOSURE
FROM LOAN
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_LOAN_EXPOSURE DESC LIMIT 1;

SELECT BRANCH_ID FROM ACCOUNTS WHERE CUSTOMER_ID =104;
